name: Auto-approve Pull Requests
on:
  pull_request_target:
    paths:
      - 'EC2/*'
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Auto-approve pull request
        uses: peter-evans/approve-pull-request-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
